// Auto-generated secret detection rules (Gitleaks/TruffleHog-class coverage)
// Patterns adapted from public corpora; generic rules use entropy gating.

export interface SecretRule {
  id: string;
  provider: string;
  severity: 'HIGH' | 'MEDIUM';
  regex: string;
  flags: string;
  entropy?: number;
  falsePositiveExclusions?: string[];
}

export const SECRET_RULES: SecretRule[] = [
  { id: 'aws-access-key', provider: 'AWS', severity: 'HIGH', flags: '', regex: '(?<![A-Z0-9])(?:AKIA|ASIA|AROA|ABIA|ACCA)[A-Z0-9]{16}(?![A-Z0-9])', entropy: 3 },
  { id: 'aws-secret-key', provider: 'AWS', severity: 'HIGH', flags: 'i', regex: 'aws.{0,20}secret.{0,20}[\'"]([A-Za-z0-9/+]{40})[\'"]' },
  { id: 'aws-session-token', provider: 'AWS', severity: 'HIGH', flags: '', regex: '(?<![A-Z0-9])ASIA[A-Z0-9]{16}(?![A-Z0-9])', entropy: 3 },
  { id: 'aws-mws-key', provider: 'AWS', severity: 'HIGH', flags: '', regex: 'amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' },
  { id: 'aws-bedrock-long-lived', provider: 'AWS', severity: 'HIGH', flags: '', regex: 'ABSK[A-Za-z0-9+/]{109,269}={0,2}' },
  { id: 'github-pat-classic', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'ghp_[A-Za-z0-9]{36}' },
  { id: 'github-pat-fine-grained', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'github_pat_[A-Za-z0-9_]{82}' },
  { id: 'github-oauth', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'gho_[A-Za-z0-9]{36}' },
  { id: 'github-app-token', provider: 'GitHub', severity: 'HIGH', flags: '', regex: '(?:ghu|ghs)_[0-9a-zA-Z]{36}' },
  { id: 'github-refresh-token', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'ghr_[0-9a-zA-Z]{36}' },
  { id: 'github_token', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'ghp_[A-Za-z0-9]{20,}' },
  { id: 'gitlab-pat', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glpat-[0-9a-zA-Z\\-_]{20,}' },
  { id: 'gitlab-cicd-job-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}' },
  { id: 'gitlab-deploy-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'gldt-[0-9a-zA-Z\\-_]{20,}' },
  { id: 'gitlab-runner-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glrt-[0-9a-zA-Z\\-_]{20,}' },
  { id: 'circleci-token', provider: 'CircleCI', severity: 'HIGH', flags: '', regex: 'CCIPAT_[a-zA-Z0-9]{32,}' },
  { id: 'travis-ci-token', provider: 'Travis CI', severity: 'HIGH', flags: '', regex: '[a-zA-Z0-9]{22}_[a-zA-Z0-9]{22}' },
  { id: 'jenkins-token', provider: 'Jenkins', severity: 'HIGH', flags: 'i', regex: 'jenkins.{0,10}(?:api|token).{0,10}[\'"]([a-f0-9]{32,})[\'"]' },
  { id: 'openai-api-key', provider: 'OpenAI', severity: 'HIGH', flags: '', regex: 'sk-[A-Za-z0-9]{20}T3BlbkFJ[A-Za-z0-9]{20}' },
  { id: 'openai-api-key-v2', provider: 'OpenAI', severity: 'HIGH', flags: '', regex: 'sk-proj-[A-Za-z0-9_-]{40,}' },
  { id: 'sk-token-arg', provider: 'OpenAI', severity: 'HIGH', flags: '', regex: 'sk-[A-Za-z0-9]{20,}' },
  { id: 'anthropic-api-key', provider: 'Anthropic', severity: 'HIGH', flags: '', regex: 'sk-ant-[A-Za-z0-9_-]{93}' },
  { id: 'huggingface-token', provider: 'HuggingFace', severity: 'HIGH', flags: '', regex: 'hf_[A-Za-z0-9]{34,}' },
  { id: 'replicate-api-token', provider: 'Replicate', severity: 'HIGH', flags: '', regex: 'r8_[A-Za-z0-9]{37,}' },
  { id: 'groq-api-key', provider: 'Groq', severity: 'HIGH', flags: '', regex: 'gsk_[A-Za-z0-9]{52,}' },
  { id: 'google-api-key', provider: 'Google', severity: 'HIGH', flags: '', regex: 'AIza[0-9A-Za-z_-]{35}' },
  { id: 'google-oauth-secret', provider: 'Google', severity: 'HIGH', flags: '', regex: 'GOCSPX-[A-Za-z0-9_-]{28}' },
  { id: 'gcp-service-account-json', provider: 'Google', severity: 'HIGH', flags: '', regex: '"type"\\s*:\\s*"service_account"' },
  { id: 'azure-storage-key', provider: 'Azure', severity: 'HIGH', flags: '', regex: 'DefaultEndpointsProtocol=https;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/]{86}==' },
  { id: 'azure-client-secret', provider: 'Azure', severity: 'HIGH', flags: '', regex: '[a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34}' },
  { id: 'azure-sas-token', provider: 'Azure', severity: 'HIGH', flags: '', regex: '[?&]sig=[A-Za-z0-9%+/=]{20,}' },
  { id: 'digitalocean-pat', provider: 'DigitalOcean', severity: 'HIGH', flags: '', regex: 'dop_v1_[a-f0-9]{64}' },
  { id: 'digitalocean-access-token', provider: 'DigitalOcean', severity: 'HIGH', flags: '', regex: 'doo_v1_[a-f0-9]{64}' },
  { id: 'cloudflare-origin-ca-key', provider: 'Cloudflare', severity: 'HIGH', flags: '', regex: 'v1\\.0-[a-f0-9]{24}-[a-f0-9]{146}' },
  { id: 'heroku-api-key', provider: 'Heroku', severity: 'HIGH', flags: 'i', regex: 'heroku.{0,20}[\'"]([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})[\'"]' },
  { id: 'stripe-secret-key', provider: 'Stripe', severity: 'HIGH', flags: '', regex: 'sk_live_[0-9a-zA-Z]{24,}' },
  { id: 'stripe-restricted-key', provider: 'Stripe', severity: 'HIGH', flags: '', regex: 'rk_live_[0-9a-zA-Z]{24,}' },
  { id: 'stripe-publishable-key', provider: 'Stripe', severity: 'MEDIUM', flags: '', regex: 'pk_live_[0-9a-zA-Z]{24,}' },
  { id: 'stripe-test-secret', provider: 'Stripe', severity: 'MEDIUM', flags: '', regex: 'sk_test_[0-9a-zA-Z]{24,}' },
  { id: 'square-access-token', provider: 'Square', severity: 'HIGH', flags: '', regex: 'sq0atp-[0-9A-Za-z\\-_]{22}' },
  { id: 'square-oauth-secret', provider: 'Square', severity: 'HIGH', flags: '', regex: 'sq0csp-[0-9A-Za-z\\-_]{43}' },
  { id: 'paypal-client-id', provider: 'PayPal', severity: 'MEDIUM', flags: '', regex: 'A[A-Za-z0-9_-]{79}' },
  { id: 'braintree-access-token', provider: 'Braintree', severity: 'HIGH', flags: '', regex: 'access_token\\$[a-z0-9]{16}\\$[a-f0-9]{32}' },
  { id: 'slack-bot-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xoxb-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24}' },
  { id: 'slack-user-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xoxp-[0-9]{10,13}-[0-9]{10,13}-[A-Za-z0-9]{24}' },
  { id: 'slack-app-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xapp-[0-9]+-[A-Z0-9]+-[0-9]+-[a-z0-9]+' },
  { id: 'slack-webhook', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'https://hooks\\.slack\\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+' },
  { id: 'discord-bot-token', provider: 'Discord', severity: 'HIGH', flags: '', regex: '[MN][A-Za-z\\d]{23,}\\.[\\w-]{6}\\.[\\w-]{27,}' },
  { id: 'discord-webhook', provider: 'Discord', severity: 'HIGH', flags: '', regex: 'https://discord(?:app)?\\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+' },
  { id: 'telegram-bot-token', provider: 'Telegram', severity: 'HIGH', flags: '', regex: '[0-9]{8,10}:[A-Za-z0-9_-]{35}' },
  { id: 'teams-webhook', provider: 'Microsoft Teams', severity: 'HIGH', flags: '', regex: 'https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[A-Za-z0-9@/-]+' },
  { id: 'sendgrid-api-key', provider: 'SendGrid', severity: 'HIGH', flags: '', regex: 'SG\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9_-]{43}' },
  { id: 'mailgun-api-key', provider: 'Mailgun', severity: 'HIGH', flags: '', regex: 'key-[0-9a-zA-Z]{32}' },
  { id: 'twilio-auth-token', provider: 'Twilio', severity: 'HIGH', flags: 'i', regex: 'twilio.{0,20}auth.{0,20}token.{0,10}[\'"]([a-z0-9]{32})[\'"]' },
  { id: 'twilio-api-key', provider: 'Twilio', severity: 'HIGH', flags: '', regex: 'SK[0-9a-fA-F]{32}' },
  { id: 'postmark-api-token', provider: 'Postmark', severity: 'HIGH', flags: '', regex: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' },
  { id: 'postgres-url', provider: 'Database', severity: 'HIGH', flags: '', regex: 'postgres(?:ql)?://[^:]+:[^@\\s]+@[^\\s]+', entropy: 3 },
  { id: 'mysql-url', provider: 'Database', severity: 'HIGH', flags: '', regex: 'mysql://[^:]+:[^@\\s]+@[^\\s]+', entropy: 3 },
  { id: 'mongodb-url', provider: 'Database', severity: 'HIGH', flags: '', regex: 'mongodb(?:\\+srv)?://[^:]+:[^@\\s]+@[^\\s]+', entropy: 3 },
  { id: 'redis-url', provider: 'Database', severity: 'HIGH', flags: '', regex: 'redis://:?[^@\\s]+@[^\\s]+', entropy: 3 },
  { id: 'amqp-url', provider: 'Database', severity: 'HIGH', flags: '', regex: 'amqps?://[^:]+:[^@\\s]+@[^\\s]+', entropy: 3 },
  { id: 'jdbc-url', provider: 'Database', severity: 'HIGH', flags: 'i', regex: 'jdbc:[a-z]+://[^\\s;]+(?:;[^\\s]*)?password=[^\\s;&]+', entropy: 3 },
  { id: 'db-url-generic', provider: 'Database', severity: 'HIGH', flags: 'i', regex: '(?:DATABASE_URL|DB_URL|DATABASE_URI)\\s*[=:]\\s*([a-z]+://[^@:\\s]+:[^@\\s]+@[^\\s]+)', entropy: 3 },
  { id: 'generic-private-key', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----' },
  { id: 'rsa_private', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN RSA PRIVATE KEY-----' },
  { id: 'ec-private-key', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN EC PRIVATE KEY-----' },
  { id: 'openssh-private-key', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN OPENSSH PRIVATE KEY-----' },
  { id: 'dsa-private-key', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN DSA PRIVATE KEY-----' },
  { id: 'pgp-private-key', provider: 'Generic', severity: 'HIGH', flags: '', regex: '-----BEGIN PGP PRIVATE KEY BLOCK-----' },
  { id: 'bip39-mnemonic-hint', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: '(?:mnemonic|seed[_-]?phrase)\\s*[:=]\\s*[\'"]([a-z]+(?:\\s+[a-z]+){11,23})[\'"]' },
  { id: 'jwt-secret', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'jwt[_-]?secret\\s*[=:]\\s*[\'"]?[a-zA-Z0-9\\-_]{20,}[\'"]?' },
  { id: 'jwt-bearer-token', provider: 'Generic', severity: 'MEDIUM', flags: '', regex: 'eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}', entropy: 3.5 },
  { id: 'oauth-client-secret', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'client[_-]?secret\\s*[:=]\\s*[\'"]([A-Za-z0-9_\\-]{16,})[\'"]', entropy: 3 },
  { id: 'session-secret', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'session[_-]?secret\\s*[:=]\\s*[\'"]([A-Za-z0-9_\\-]{16,})[\'"]', entropy: 3 },
  { id: 'npm-token', provider: 'npm', severity: 'HIGH', flags: '', regex: '(?:npm_|//registry\\.npmjs\\.org/:_authToken=)[A-Za-z0-9_-]{36}' },
  { id: 'pypi-api-token', provider: 'PyPI', severity: 'HIGH', flags: '', regex: 'pypi-[A-Za-z0-9_-]{100,}' },
  { id: 'rubygems-api-key', provider: 'RubyGems', severity: 'HIGH', flags: '', regex: 'rubygems_[a-f0-9]{48}' },
  { id: 'nuget-api-key', provider: 'NuGet', severity: 'HIGH', flags: '', regex: 'oy2[a-z0-9]{43}' },
  { id: 'generic-api-key', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: '(?:api[_-]?key|apikey|api[_-]?secret)\\s*[:=]\\s*[\'"]?([A-Za-z0-9_\\-]{20,})[\'"]?', entropy: 3.5, falsePositiveExclusions: ['your.api.key', 'placeholder', 'example', 'xxxx', '\\*{4,}'] },
  { id: 'generic-password', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'password\\s*[:=]\\s*[\'"]([^\'"]{8,})[\'"]', entropy: 2.5, falsePositiveExclusions: ['changeme', 'password123', 'example'] },
  { id: 'password_assign', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'password\\s*=\\s*([^\\s]{8,})', entropy: 2.5, falsePositiveExclusions: ['changeme', 'password123', 'example'] },
  { id: 'api_key_header', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: 'api[_-]?key\\s*=\\s*([A-Za-z0-9_\\-]{16,})', entropy: 3 },
  { id: 'bearer_token', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: '(?:token|auth|bearer)\\s*=\\s*([A-Za-z0-9_\\-]{16,})', entropy: 3 },
  { id: 'high-entropy-assignment', provider: 'Generic', severity: 'MEDIUM', flags: 'i', regex: '(?:secret|token|credential)\\s*[:=]\\s*[\'"]([A-Za-z0-9+/=_\\-]{24,})[\'"]', entropy: 4, falsePositiveExclusions: ['placeholder', 'example', 'changeme', 'your-secret'] },
  { id: 'uri-credentials', provider: 'Generic', severity: 'HIGH', flags: '', regex: '[a-z][a-z0-9+-]+://[^:@\\s]+:[^:@\\s]+@[^\\s]+', entropy: 3.5, falsePositiveExclusions: ['localhost', '127\\.0\\.0\\.1', '::1', 'example\\.com', 'test\\.com', '\\.local', '\\.internal'] },
  { id: 'base64_large', provider: 'Generic', severity: 'MEDIUM', flags: '', regex: '(?:^|[^A-Za-z0-9+/])([A-Za-z0-9+/]{60,}={0,2})' },
  { id: 'databricks-token', provider: 'Databricks', severity: 'HIGH', flags: '', regex: 'dapi[a-h0-9]{32}' },
  { id: 'vault-token', provider: 'HashiCorp', severity: 'HIGH', flags: '', regex: '(?:hvs|s\\.[A-Za-z0-9]{24})\\.[A-Za-z0-9_-]{6,}' },
  { id: '1password-secret-key', provider: '1Password', severity: 'HIGH', flags: '', regex: '\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b', entropy: 3.8 },
  { id: '1password-service-account-token', provider: '1Password', severity: 'MEDIUM', flags: '', regex: 'ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}', entropy: 4 },
  { id: 'adafruit-api-key', provider: 'Adafruit', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:adafruit)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9_-]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'adobe-client-id', provider: 'Adobe', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:adobe)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'age-secret-key', provider: 'Age', severity: 'HIGH', flags: '', regex: 'AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}' },
  { id: 'airtable-api-key', provider: 'Airtable', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:airtable)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{17})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'airtable-personnal-access-token', provider: 'Airtable', severity: 'HIGH', flags: '', regex: '\\b(pat[a-zA-Z0-9]{14}\\.[a-f0-9]{64})\\b' },
  { id: 'algolia-api-key', provider: 'Algolia', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:algolia)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'alibaba-secret-key', provider: 'Alibaba', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:alibaba)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{30})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'anthropic-admin-api-key', provider: 'Anthropic', severity: 'HIGH', flags: '', regex: '\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'artifactory-api-key', provider: 'Artifactory', severity: 'MEDIUM', flags: '', regex: '\\bAKCp[A-Za-z0-9]{69}\\b', entropy: 4.5 },
  { id: 'artifactory-reference-token', provider: 'Artifactory', severity: 'MEDIUM', flags: '', regex: '\\bcmVmd[A-Za-z0-9]{59}\\b', entropy: 4.5 },
  { id: 'asana-client-id', provider: 'Asana', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'asana-client-secret', provider: 'Asana', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'atlassian-api-token', provider: 'Atlassian', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:(?:ATLASSIAN|[Aa]tlassian)|(?:CONFLUENCE|[Cc]onfluence)|(?:JIRA|[Jj]ira))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[`\'"\\s;]|\\\\[nr]|$)|\\b(ATATT3[A-Za-z0-9_\\-=]{186})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3.5 },
  { id: 'aws-access-token', provider: 'AWS', severity: 'HIGH', flags: '', regex: '\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b', entropy: 3 },
  { id: 'aws-amazon-bedrock-api-key-long-lived', provider: 'AWS', severity: 'HIGH', flags: '', regex: '\\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'aws-amazon-bedrock-api-key-short-lived', provider: 'AWS', severity: 'HIGH', flags: '', regex: 'bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t', entropy: 3 },
  { id: 'azure-ad-client-secret', provider: 'Azure', severity: 'HIGH', flags: '', regex: '(?:^|[\\\\\'"`\\s>=:(,)])([a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\\\\'"`\\s<),])', entropy: 3 },
  { id: 'beamer-api-token', provider: 'Beamer', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:beamer)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(b_[a-z0-9=_\\-]{44})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'bitbucket-client-id', provider: 'Bitbucket', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'bitbucket-client-secret', provider: 'Bitbucket', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'bittrex-access-key', provider: 'Bittrex', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'bittrex-secret-key', provider: 'Bittrex', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'cisco-meraki-api-key', provider: 'Cisco', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:[\\w.-]{0,50}?(?:(?:[Mm]eraki|MERAKI))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'clickhouse-cloud-api-secret-key', provider: 'Clickhouse', severity: 'HIGH', flags: '', regex: '\\b(4b1d[A-Za-z0-9]{38})\\b', entropy: 3 },
  { id: 'clojars-api-token', provider: 'Clojars', severity: 'HIGH', flags: 'i', regex: 'CLOJARS_[a-z0-9]{60}', entropy: 2 },
  { id: 'cloudflare-api-key', provider: 'Cloudflare', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'cloudflare-global-api-key', provider: 'Cloudflare', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{37})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'codecov-access-token', provider: 'Codecov', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:codecov)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'cohere-api-token', provider: 'Cohere', severity: 'MEDIUM', flags: 'i', regex: '[\\w.-]{0,50}?(?:[\\w.-]{0,50}?(?:cohere|CO_API_KEY)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-zA-Z0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'coinbase-access-token', provider: 'Coinbase', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:coinbase)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9_-]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'confluent-access-token', provider: 'Confluent', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'confluent-secret-key', provider: 'Confluent', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'contentful-delivery-api-token', provider: 'Contentful', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:contentful)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{43})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'curl-auth-user', provider: 'Curl', severity: 'HIGH', flags: '', regex: '\\bcurl\\b(?:.*|.*(?:[\\r\\n]{1,2}.*){1,5})[ \\t\\n\\r](?:-u|--user)(?:=|[ \\t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|\'([^:\']{3,}:[^\']{3,})\'|((?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w$@.-]+):(?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w${}@.-]+)))(?:\\s|\\z)', entropy: 2 },
  { id: 'databricks-api-token', provider: 'Databricks', severity: 'HIGH', flags: '', regex: '\\b(dapi[a-f0-9]{32}(?:-\\d)?)(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'datadog-access-token', provider: 'Datadog', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:datadog)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'defined-networking-api-token', provider: 'Defined', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:dnkey)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(dnkey-[a-z0-9=_\\-]{26}-[a-z0-9=_\\-]{52})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'digitalocean-refresh-token', provider: 'DigitalOcean', severity: 'HIGH', flags: 'i', regex: '\\b(dor_v1_[a-f0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'discord-api-token', provider: 'Discord', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'discord-client-id', provider: 'Discord', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9]{18})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'discord-client-secret', provider: 'Discord', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'droneci-access-token', provider: 'Droneci', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'dropbox-api-token', provider: 'Dropbox', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{15})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'dropbox-long-lived-api-token', provider: 'Dropbox', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'dropbox-short-lived-api-token', provider: 'Dropbox', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'etsy-access-token', provider: 'Etsy', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:(?:ETSY|[Ee]tsy))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{24})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'facebook-access-token', provider: 'Facebook', severity: 'HIGH', flags: 'i', regex: '\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'facebook-secret', provider: 'Facebook', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'fastly-api-token', provider: 'Fastly', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'finicity-api-token', provider: 'Finicity', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'finicity-client-secret', provider: 'Finicity', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{20})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'finnhub-access-token', provider: 'Finnhub', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{20})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'flickr-access-token', provider: 'Flickr', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'flyio-access-token', provider: 'Flyio', severity: 'MEDIUM', flags: '', regex: '\\b((?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+\\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\\/]{100,}={0,3}))(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'freemius-secret-key', provider: 'Freemius', severity: 'HIGH', flags: 'i', regex: '["\']secret_key["\']\\s*=>\\s*["\'](sk_[\\S]{29})["\']' },
  { id: 'freshbooks-access-token', provider: 'Freshbooks', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'gcp-api-key', provider: 'Google', severity: 'MEDIUM', flags: '', regex: '\\b(AIza[\\w-]{35})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'github-fine-grained-pat', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'github_pat_\\w{82}', entropy: 3 },
  { id: 'github-pat', provider: 'GitHub', severity: 'HIGH', flags: '', regex: 'ghp_[0-9a-zA-Z]{36}', entropy: 3 },
  { id: 'gitlab-feature-flag-client-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glffct-[0-9a-zA-Z_\\-]{20}', entropy: 3 },
  { id: 'gitlab-feed-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glft-[0-9a-zA-Z_\\-]{20}', entropy: 3 },
  { id: 'gitlab-incoming-mail-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glimt-[0-9a-zA-Z_\\-]{25}', entropy: 3 },
  { id: 'gitlab-kubernetes-agent-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glagent-[0-9a-zA-Z_\\-]{50}', entropy: 3 },
  { id: 'gitlab-oauth-app-secret', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'gloas-[0-9a-zA-Z_\\-]{64}', entropy: 3 },
  { id: 'gitlab-pat-routable', provider: 'GitLab', severity: 'MEDIUM', flags: '', regex: '\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b', entropy: 4 },
  { id: 'gitlab-ptt', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glptt-[0-9a-f]{40}', entropy: 3 },
  { id: 'gitlab-rrt', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'GR1348941[\\w-]{20}', entropy: 3 },
  { id: 'gitlab-runner-authentication-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glrt-[0-9a-zA-Z_\\-]{20}', entropy: 3 },
  { id: 'gitlab-runner-authentication-token-routable', provider: 'GitLab', severity: 'MEDIUM', flags: '', regex: '\\bglrt-t\\d_[0-9a-zA-Z_\\-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b', entropy: 4 },
  { id: 'gitlab-scim-token', provider: 'GitLab', severity: 'HIGH', flags: '', regex: 'glsoat-[0-9a-zA-Z_\\-]{20}', entropy: 3 },
  { id: 'gitlab-session-cookie', provider: 'GitLab', severity: 'HIGH', flags: '', regex: '_gitlab_session=[0-9a-z]{32}', entropy: 3 },
  { id: 'gitter-access-token', provider: 'Gitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:gitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'grafana-api-key', provider: 'Grafana', severity: 'HIGH', flags: 'i', regex: '\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'grafana-cloud-api-token', provider: 'Grafana', severity: 'HIGH', flags: 'i', regex: '\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'grafana-service-account-token', provider: 'Grafana', severity: 'HIGH', flags: 'i', regex: '\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'harness-api-key', provider: 'Harness', severity: 'HIGH', flags: '', regex: '(?:pat|sat)\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9]{24}\\.[a-zA-Z0-9]{20}' },
  { id: 'hashicorp-tf-api-token', provider: 'Hashicorp', severity: 'HIGH', flags: 'i', regex: '[a-z0-9]{14}\\.(?:atlasv1)\\.[a-z0-9\\-_=]{60,70}', entropy: 3.5 },
  { id: 'hashicorp-tf-password', provider: 'Hashicorp', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:administrator_login_password|password)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}("[a-z0-9=_\\-]{8,20}")(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'heroku-api-key-v2', provider: 'Heroku', severity: 'MEDIUM', flags: '', regex: '\\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'hubspot-api-key', provider: 'Hubspot', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:hubspot)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'huggingface-access-token', provider: 'HuggingFace', severity: 'HIGH', flags: 'i', regex: '\\b(hf_[a-z]{34})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'huggingface-organization-api-token', provider: 'HuggingFace', severity: 'HIGH', flags: 'i', regex: '\\b(api_org_[a-z]{34})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'infracost-api-token', provider: 'Infracost', severity: 'HIGH', flags: '', regex: '\\b(ico-[a-zA-Z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'intercom-api-key', provider: 'Intercom', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:intercom)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{60})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'jfrog-api-key', provider: 'Jfrog', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{73})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'jfrog-identity-token', provider: 'Jfrog', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'jwt', provider: 'Generic', severity: 'HIGH', flags: '', regex: '\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'kraken-access-token', provider: 'Kraken', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:kraken)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9\\/=_\\+\\-]{80,90})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'kubernetes-secret-yaml', provider: 'Kubernetes', severity: 'HIGH', flags: 'is', regex: '(?:\\bkind:[ \\t]*["\']?\\bsecret\\b["\']?.{0,200}?\\bdata:.{0,100}?\\s+([\\w.-]+:(?:[ \\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ \\t\\w"|$:=,.-]+}}|""|\'\'))|\\bdata:.{0,100}?\\s+([\\w.-]+:(?:[ \\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ \\t\\w"|$:=,.-]+}}|""|\'\')).{0,200}?\\bkind:[ \\t]*["\']?\\bsecret\\b["\']?)' },
  { id: 'kucoin-access-token', provider: 'Kucoin', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{24})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'kucoin-secret-key', provider: 'Kucoin', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'launchdarkly-access-token', provider: 'Launchdarkly', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:launchdarkly)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'linear-client-secret', provider: 'Linear', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:linear)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'linkedin-client-id', provider: 'LinkedIn', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{14})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'linkedin-client-secret', provider: 'LinkedIn', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'lob-api-key', provider: 'Lob', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'lob-pub-api-key', provider: 'Lob', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'looker-client-id', provider: 'Looker', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{20})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'looker-client-secret', provider: 'Looker', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{24})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mailchimp-api-key', provider: 'Mailchimp', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:MailchimpSDK.initialize|mailchimp)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mailgun-private-api-token', provider: 'Mailgun', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(key-[a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mailgun-pub-key', provider: 'Mailgun', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mailgun-signing-key', provider: 'Mailgun', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mapbox-api-token', provider: 'Mapbox', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:mapbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'mattermost-access-token', provider: 'Mattermost', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:mattermost)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{26})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'maxmind-license-key', provider: 'Maxmind', severity: 'MEDIUM', flags: '', regex: '\\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'messagebird-api-token', provider: 'Age', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{25})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'messagebird-client-id', provider: 'Age', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'microsoft-teams-webhook', provider: 'Microsoft Teams', severity: 'HIGH', flags: '', regex: 'https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}' },
  { id: 'netlify-access-token', provider: 'Netlify', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:netlify)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9=_\\-]{40,46})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'new-relic-browser-api-token', provider: 'New', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'new-relic-insert-key', provider: 'New', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'new-relic-user-api-id', provider: 'New', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'new-relic-user-api-key', provider: 'New', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(NRAK-[a-z0-9]{27})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'notion-api-token', provider: 'Notion', severity: 'MEDIUM', flags: '', regex: '\\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'npm-access-token', provider: 'npm', severity: 'HIGH', flags: 'i', regex: '\\b(npm_[a-z0-9]{36})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'nuget-config-password', provider: 'NuGet', severity: 'HIGH', flags: 'i', regex: '', entropy: 1 },
  { id: 'octopus-deploy-api-key', provider: 'Octopus', severity: 'HIGH', flags: '', regex: '\\b(API-[A-Z0-9]{26})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'okta-access-token', provider: 'Okta', severity: 'MEDIUM', flags: 'i', regex: '[\\w.-]{0,50}?(?:[\\w.-]{0,50}?(?:(?:[Oo]kta|OKTA))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(00[\\w=\\-]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'openshift-user-token', provider: 'Openshift', severity: 'HIGH', flags: '', regex: '\\b(sha256~[\\w-]{43})(?:[^\\w-]|\\z)', entropy: 3.5 },
  { id: 'perplexity-api-key', provider: 'Perplexity', severity: 'MEDIUM', flags: '', regex: '\\b(pplx-[a-zA-Z0-9]{48})(?:[`\'"\\s;]|\\\\[nr]|$|\\b)', entropy: 4 },
  { id: 'plaid-api-token', provider: 'Plaid', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'plaid-client-id', provider: 'Plaid', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{24})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3.5 },
  { id: 'plaid-secret-key', provider: 'Plaid', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{30})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3.5 },
  { id: 'planetscale-oauth-token', provider: 'Generic', severity: 'HIGH', flags: '', regex: '\\b(pscale_oauth_[\\w=\\.-]{32,64})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'prefect-api-token', provider: 'Prefect', severity: 'HIGH', flags: '', regex: '\\b(pnu_[a-zA-Z0-9]{36})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'private-key', provider: 'Generic', severity: 'HIGH', flags: 'i', regex: '-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]{64,}?KEY(?: BLOCK)?-----' },
  { id: 'privateai-api-token', provider: 'Generic', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:[\\w.-]{0,50}?(?:private[_-]?ai)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{32})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'pulumi-api-token', provider: 'Pulumi', severity: 'HIGH', flags: '', regex: '\\b(pul-[a-f0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'pypi-upload-token', provider: 'PyPI', severity: 'HIGH', flags: '', regex: 'pypi-AgEIcHlwaS5vcmc[\\w-]{50,1000}', entropy: 3 },
  { id: 'rapidapi-access-token', provider: 'Rapidapi', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:rapidapi)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9_-]{50})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'readme-api-token', provider: 'Readme', severity: 'HIGH', flags: '', regex: '\\b(rdme_[a-z0-9]{70})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'rubygems-api-token', provider: 'RubyGems', severity: 'HIGH', flags: '', regex: '\\b(rubygems_[a-f0-9]{48})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'scalingo-api-token', provider: 'Scalingo', severity: 'HIGH', flags: '', regex: '\\b(tk-us-[\\w-]{48})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'sendbird-access-id', provider: 'Sendbird', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'sendbird-access-token', provider: 'Sendbird', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'sentry-access-token', provider: 'Sentry', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:sentry)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'sentry-org-token', provider: 'Sentry', severity: 'MEDIUM', flags: '', regex: '\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|\\z)', entropy: 4.5 },
  { id: 'sentry-user-token', provider: 'Sentry', severity: 'HIGH', flags: '', regex: '\\b(sntryu_[a-f0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3.5 },
  { id: 'settlemint-application-access-token', provider: 'Settlemint', severity: 'HIGH', flags: '', regex: '\\b(sm_aat_[a-zA-Z0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'settlemint-personal-access-token', provider: 'Settlemint', severity: 'HIGH', flags: '', regex: '\\b(sm_pat_[a-zA-Z0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'settlemint-service-access-token', provider: 'Settlemint', severity: 'HIGH', flags: '', regex: '\\b(sm_sat_[a-zA-Z0-9]{16})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'shippo-api-token', provider: 'Shippo', severity: 'HIGH', flags: '', regex: '\\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'shopify-access-token', provider: 'Shopify', severity: 'HIGH', flags: '', regex: 'shpat_[a-fA-F0-9]{32}', entropy: 2 },
  { id: 'shopify-custom-access-token', provider: 'Shopify', severity: 'HIGH', flags: '', regex: 'shpca_[a-fA-F0-9]{32}', entropy: 2 },
  { id: 'shopify-private-app-access-token', provider: 'Generic', severity: 'HIGH', flags: '', regex: 'shppa_[a-fA-F0-9]{32}', entropy: 2 },
  { id: 'shopify-shared-secret', provider: 'Shopify', severity: 'HIGH', flags: '', regex: 'shpss_[a-fA-F0-9]{32}', entropy: 2 },
  { id: 'sidekiq-secret', provider: 'Sidekiq', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'sidekiq-sensitive-url', provider: 'Sidekiq', severity: 'HIGH', flags: 'i', regex: '\\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\\/|\\#|\\?|:]|$)' },
  { id: 'slack-config-access-token', provider: 'Slack', severity: 'HIGH', flags: 'i', regex: 'xoxe.xox[bp]-\\d-[A-Z0-9]{163,166}', entropy: 2 },
  { id: 'slack-config-refresh-token', provider: 'Slack', severity: 'HIGH', flags: 'i', regex: 'xoxe-\\d-[A-Z0-9]{146}', entropy: 2 },
  { id: 'slack-legacy-bot-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}', entropy: 2 },
  { id: 'slack-legacy-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+', entropy: 2 },
  { id: 'slack-legacy-workspace-token', provider: 'Slack', severity: 'HIGH', flags: '', regex: 'xox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}', entropy: 2 },
  { id: 'slack-webhook-url', provider: 'Slack', severity: 'HIGH', flags: '', regex: '(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}' },
  { id: 'snyk-api-token', provider: 'Snyk', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'sonar-api-token', provider: 'SonarQube', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\\-]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'sourcegraph-access-token', provider: 'Sourcegraph', severity: 'HIGH', flags: 'i', regex: '\\b(\\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})\\b)(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'squarespace-access-token', provider: 'Square', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:squarespace)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'stripe-access-token', provider: 'Stripe', severity: 'HIGH', flags: '', regex: '\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 2 },
  { id: 'sumologic-access-id', provider: 'Sumologic', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:[\\w.-]{0,50}?(?:(?:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(su[a-zA-Z0-9]{12})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'sumologic-access-token', provider: 'Sumologic', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:(?:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{64})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3 },
  { id: 'telegram-bot-api-token', provider: 'Telegram', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:telegr)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9]{5,16}:(?:A)[a-z0-9_\\-]{34})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'travisci-access-token', provider: 'Travis CI', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:travis)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{22})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitch-api-token', provider: 'Twitch', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitch)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{30})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitter-access-secret', provider: 'Twitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{45})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitter-access-token', provider: 'Twitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitter-api-key', provider: 'Twitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{25})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitter-api-secret', provider: 'Twitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{50})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'twitter-bearer-token', provider: 'Twitter', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'typeform-api-token', provider: 'Typeform', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:typeform)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(tfp_[a-z0-9\\-_\\.=]{59})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'vault-batch-token', provider: 'HashiCorp', severity: 'MEDIUM', flags: '', regex: '\\b(hvb\\.[\\w-]{138,300})(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 4 },
  { id: 'vault-service-token', provider: 'HashiCorp', severity: 'HIGH', flags: 'i', regex: '\\b((?:hvs\\.[\\w-]{90,120}|s\\.[a-z0-9]{24}))(?:[`\'"\\s;]|\\\\[nr]|$)', entropy: 3.5 },
  { id: 'yandex-access-token', provider: 'Yandex', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'yandex-api-key', provider: 'Yandex', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(AQVN[A-Za-z0-9_\\-]{35,38})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'yandex-aws-access-token', provider: 'AWS', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}(YC[a-zA-Z0-9_\\-]{38})(?:[`\'"\\s;]|\\\\[nr]|$)' },
  { id: 'zendesk-secret-key', provider: 'Zendesk', severity: 'HIGH', flags: 'i', regex: '[\\w.-]{0,50}?(?:zendesk)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[`\'"\\s=]{0,5}([a-z0-9]{40})(?:[`\'"\\s;]|\\\\[nr]|$)' },
];
